# cotire.cmake 1.7.10 generated file
# /home/jopper/veyon/cmake/server/veyon-server_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/jopper/veyon/cmake/modules/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.10")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELWITHDEBINFO "QT_DEPRECATED_WARNINGS;QT_DISABLE_DEPRECATED_BEFORE=0x050600;_FORTIFY_SOURCE=2;QT_GUI_LIB;QT_NETWORK_LIB;QT_WIDGETS_LIB;QT_CONCURRENT_LIB;QT_CORE_LIB;$<$<NOT:$<CONFIG:Debug>>:QT_NO_DEBUG>;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_RELWITHDEBINFO "-Wall;-fno-exceptions;-std=c++11;-fstack-protector-strong;-O2;-g;-std=gnu++11")
set (COTIRE_TARGET_CONFIGURATION_TYPES "relwithdebinfo")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/home/jopper/veyon")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELWITHDEBINFO "/usr/x86_64-w64-mingw32/include;/home/jopper/veyon/core/include;/home/jopper/veyon/cmake/core/include;/home/jopper/veyon/3rdparty/libvncserver;/usr/x86_64-w64-mingw32/include/Qca-qt5/QtCrypto;/home/jopper/veyon/cmake/server;/home/jopper/veyon/server/src;/usr/x86_64-w64-mingw32/include/qt5/;/usr/x86_64-w64-mingw32/include/qt5/QtGui;/usr/x86_64-w64-mingw32/include/qt5/QtNetwork;/usr/x86_64-w64-mingw32/include/qt5/QtWidgets;/usr/x86_64-w64-mingw32/include/qt5/QtConcurrent;/usr/x86_64-w64-mingw32/include/qt5/QtCore;/usr/x86_64-w64-mingw32/.//mkspecs/win32-g++")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/home/jopper/veyon/server/src/ComputerControlClient.cpp;/home/jopper/veyon/server/src/ComputerControlServer.cpp;/home/jopper/veyon/server/src/ServerAccessControlManager.cpp;/home/jopper/veyon/server/src/ServerAuthenticationManager.cpp;/home/jopper/veyon/server/src/VeyonServerProtocol.cpp;/home/jopper/veyon/server/src/VncProxyConnection.cpp;/home/jopper/veyon/server/src/VncProxyServer.cpp;/home/jopper/veyon/server/src/VncServer.cpp;/home/jopper/veyon/server/src/main.cpp;/home/jopper/veyon/cmake/server/src/moc_ComputerControlClient.cpp;/home/jopper/veyon/cmake/server/src/moc_ComputerControlServer.cpp;/home/jopper/veyon/cmake/server/src/moc_ServerAccessControlManager.cpp;/home/jopper/veyon/cmake/server/src/moc_ServerAuthenticationManager.cpp;/home/jopper/veyon/cmake/server/src/moc_VeyonServerProtocol.cpp;/home/jopper/veyon/cmake/server/src/moc_VncProxyConnection.cpp;/home/jopper/veyon/cmake/server/src/moc_VncProxyConnectionFactory.cpp;/home/jopper/veyon/cmake/server/src/moc_VncProxyServer.cpp;/home/jopper/veyon/cmake/server/src/moc_VncServer.cpp")
set (COTIRE_TARGET_UNITY_DEPENDS "/home/jopper/veyon/cmake/server/src/moc_ComputerControlClient.cpp;/home/jopper/veyon/cmake/server/src/moc_ComputerControlServer.cpp;/home/jopper/veyon/cmake/server/src/moc_ServerAccessControlManager.cpp;/home/jopper/veyon/cmake/server/src/moc_ServerAuthenticationManager.cpp;/home/jopper/veyon/cmake/server/src/moc_VeyonServerProtocol.cpp;/home/jopper/veyon/cmake/server/src/moc_VncProxyConnection.cpp;/home/jopper/veyon/cmake/server/src/moc_VncProxyConnectionFactory.cpp;/home/jopper/veyon/cmake/server/src/moc_VncProxyServer.cpp;/home/jopper/veyon/cmake/server/src/moc_VncServer.cpp;/home/jopper/veyon/cmake/server/winrc.obj")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "relwithdebinfo")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "7.3.0")
set (CMAKE_CXX_COMPILER "/usr/bin/x86_64-w64-mingw32-g++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
