# cotire.cmake 1.7.10 generated file
# /home/jopper/veyon/cmake/plugins/ldap/ldap_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/jopper/veyon/cmake/modules/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.10")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELWITHDEBINFO "ldap_EXPORTS;QT_DEPRECATED_WARNINGS;QT_DISABLE_DEPRECATED_BEFORE=0x050600;_FORTIFY_SOURCE=2;QT_WIDGETS_LIB;QT_NETWORK_LIB;QT_GUI_LIB;QT_CORE_LIB;QT_NO_DEBUG;QT_CONCURRENT_LIB;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_RELWITHDEBINFO "-Wall;-fno-exceptions;-std=c++11;-fstack-protector-strong;-O2;-g;-std=gnu++11")
set (COTIRE_TARGET_CONFIGURATION_TYPES "relwithdebinfo")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/home/jopper/veyon")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELWITHDEBINFO "/usr/x86_64-w64-mingw32/include;/home/jopper/veyon/core/include;/home/jopper/veyon/cmake/core/include;/home/jopper/veyon/3rdparty/libvncserver;/usr/x86_64-w64-mingw32/include/Qca-qt5/QtCrypto;/home/jopper/veyon/cmake/plugins/ldap;/home/jopper/veyon/plugins/ldap;/usr/x86_64-w64-mingw32/include/qt5/;/usr/x86_64-w64-mingw32/include/qt5/QtWidgets;/usr/x86_64-w64-mingw32/include/qt5/QtNetwork;/usr/x86_64-w64-mingw32/include/qt5/QtGui;/usr/x86_64-w64-mingw32/include/qt5/QtCore;/usr/x86_64-w64-mingw32/.//mkspecs/win32-g++;/usr/x86_64-w64-mingw32/include/qt5/QtConcurrent")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "LdapPlugin.cpp;LdapConfiguration.cpp;LdapConfigurationPage.cpp;LdapDirectory.cpp;LdapNetworkObjectDirectory.cpp;KLdapIntegration.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ber.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldif.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldapurl.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldapserver.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldapobject.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldapconnection.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldapoperation.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldapcontrol.cpp;/home/jopper/veyon/plugins/ldap/../../3rdparty/kldap/src/ldapdn.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapPlugin.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapConfiguration.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapConfigurationPage.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapDirectory.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapNetworkObjectDirectory.cpp;/home/jopper/veyon/cmake/plugins/ldap/qrc_ldap.cpp")
set (COTIRE_TARGET_UNITY_DEPENDS "/home/jopper/veyon/cmake/plugins/ldap/moc_LdapPlugin.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapConfiguration.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapConfigurationPage.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapDirectory.cpp;/home/jopper/veyon/cmake/plugins/ldap/moc_LdapNetworkObjectDirectory.cpp;/home/jopper/veyon/cmake/plugins/ldap/qrc_ldap.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "relwithdebinfo")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "7.3.0")
set (CMAKE_CXX_COMPILER "/usr/bin/x86_64-w64-mingw32-g++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
